### ISSUE TITLE
Ui activity_movie_details не соответствует макетам в figma

### ISSUE THREAD

**Issue by ardmn** [AndroidAcademyFundamentals20ViterGroup/EugeneGxUA-homework-app#2]
**Devices:** emulator pixel 4 api level  27 & pixel api level  21

**Actual result:**
<img width="781" alt="Снимок экрана 2020-11-23 в 04 06 55" src="https://user-images.githubusercontent.com/7188636/99922573-4d208380-2d42-11eb-81fb-dd9fe847a9da.png">

**Expected result**
<img width="395" alt="Снимок экрана 2020-11-22 в 23 30 16" src="https://user-images.githubusercontent.com/7188636/99922577-51e53780-2d42-11eb-8c64-5b4f75b4fb64.png">

**Comment by EugeneGxUA** [comment]
Спасибо большое что посмотрел. Немного не понял что со шрифтами?
Тот что описание, наверное, цвет, а с остальным ?

**Comment by ardmn** [comment]
Обрати, пожалуйста внимание на стиль шрифтов, толщину букв и т.п.

**Comment by EugeneGxUA** [comment]
Я не умею правильно управлять issues flow... Я закинул мердж реквест

**Comment by ardmn** [comment]
![Uploading Снимок экрана 2020-11-23 в 15.54.02.png…]()
